import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.cpp
vectoryReconfig.c
ledApps/ledblink.c
ledApps/ejdLeds.c
crc32/crc32.c
printerServer/printerHard.cpp
wifiModule/wifiServer.cpp
transferServer/transferCore.cpp
""")

path    = [cwd, str(Dir('#'))] 
path    += [cwd + '/ledApps']
path    += [cwd + '/printerServer']
path    += [cwd + '/wifiModule']
path    += [cwd + '/transferServer']
path    += [cwd + '/crc32']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
